### ISSUE TITLE
Unable to use Faker.Cat

### ISSUE THREAD

**Issue by indocomsoft** [igas/faker#204]
I am getting this error stacktrace:
```
:erlang.function_exported(Faker.Cat.En, :name, EnUs)
       (elixir) lib/kernel.ex:3180: Kernel.function_exported?/3
       (faker) lib/faker/cat.ex:23: Faker.Cat.name/0
```

I think the `localize` macro is broken.
According to elixir docs: https://hexdocs.pm/elixir/Kernel.html#function_exported?/3, the spec is `function_exported?(module(), atom(), arity()) :: boolean()`, but instead it is being used like so in Faker `function_exported?(module, unquote(function), EnUs)`

`EnUs` is not `arity()`

**Comment by indocomsoft** [comment]
Resolved by a32f174
